-- Keys for admin push notifications, kept out of the Data API.
--
-- The notify-admin Edge Function generates the VAPID key pair on its first
-- run and stores it here, and the webhook secret is generated by Postgres,
-- so no secret ever has to be copied around by hand. After deploying the
-- function, create the two Vault entries once per project:
--
--   select vault.create_secret('https://<ref>.supabase.co/functions/v1/notify-admin', 'chat_notify_url');
--   select vault.create_secret(encode(extensions.gen_random_bytes(32), 'hex'), 'chat_webhook_secret');

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table private.push_keys (
  id integer primary key default 1 check (id = 1),
  public_key text not null,
  private_key text not null,
  created_at timestamptz not null default now()
);

-- everything the Edge Function needs, in one call (service_role only)
create or replace function public.chat_push_config()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'webhook_secret', (select decrypted_secret from vault.decrypted_secrets where name = 'chat_webhook_secret'),
    'public_key', (select public_key from private.push_keys where id = 1),
    'private_key', (select private_key from private.push_keys where id = 1)
  );
$$;

-- first writer wins, so concurrent cold starts agree on one key pair
create or replace function public.chat_save_push_keys(public_key text, private_key text)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into private.push_keys (id, public_key, private_key)
  values (1, chat_save_push_keys.public_key, chat_save_push_keys.private_key)
  on conflict (id) do nothing;
$$;

revoke execute on function public.chat_push_config() from public, anon, authenticated;
revoke execute on function public.chat_save_push_keys(text, text) from public, anon, authenticated;
grant execute on function public.chat_push_config() to service_role;
grant execute on function public.chat_save_push_keys(text, text) to service_role;
